openapi: 3.0.3
info:
  title: Book Store
  description: Service to perform CRUD operations using goa
  version: "1.0"
servers:
- url: http://localhost:8000
paths:
  /:
    post:
      tags:
      - book
      summary: create book
      description: Adds a new book to the book store.
      operationId: book#create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRequestBody'
            example:
              description: Books are human's best friend
              id: 1
              name: book1
              price: 100
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
              example:
                description: Books are human's best friend
                id: 1
                name: book1
                price: 100
  /books:
    get:
      tags:
      - book
      summary: list book
      description: List all entries
      operationId: book#list
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
                example:
                - description: Books are human's best friend
                  id: 1
                  name: book1
                  price: 100
                - description: Books are human's best friend
                  id: 1
                  name: book1
                  price: 100
                - description: Books are human's best friend
                  id: 1
                  name: book1
                  price: 100
                - description: Books are human's best friend
                  id: 1
                  name: book1
                  price: 100
              example:
              - description: Books are human's best friend
                id: 1
                name: book1
                price: 100
              - description: Books are human's best friend
                id: 1
                name: book1
                price: 100
              - description: Books are human's best friend
                id: 1
                name: book1
                price: 100
              - description: Books are human's best friend
                id: 1
                name: book1
                price: 100
components:
  schemas:
    Book:
      type: object
      properties:
        description:
          type: string
          description: Description of the book
          example: Books are human's best friend
          maxLength: 100
        id:
          type: integer
          description: ID of the book
          example: 1
        name:
          type: string
          description: Name of book
          example: book1
          maxLength: 100
        price:
          type: integer
          description: Price of the book
          example: 100
      example:
        description: Books are human's best friend
        id: 1
        name: book1
        price: 100
      required:
      - id
      - name
      - description
      - price
    CreateRequestBody:
      type: object
      properties:
        description:
          type: string
          description: Description of the book
          example: Books are human's best friend
          maxLength: 100
        id:
          type: integer
          description: ID of the book
          example: 1
        name:
          type: string
          description: Name of book
          example: book1
          maxLength: 100
        price:
          type: integer
          description: Price of the book
          example: 100
      example:
        description: Books are human's best friend
        id: 1
        name: book1
        price: 100
      required:
      - id
      - name
      - description
      - price
