swagger: "2.0"
info:
  title: Book Store
  description: Service to perform CRUD operations using goa
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /:
    post:
      tags:
      - book
      summary: create book
      description: Adds a new book to the book store.
      operationId: book#create
      parameters:
      - name: CreateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/BookCreateRequestBody'
          required:
          - id
          - name
          - description
          - price
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/BookCreateResponseBody'
      schemes:
      - http
  /book/{id}:
    delete:
      tags:
      - book
      summary: remove book
      description: Remove book from storage
      operationId: book#remove
      parameters:
      - name: id
        in: path
        description: ID of book to remove
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/BookRemoveNotFoundResponseBody'
      schemes:
      - http
    patch:
      tags:
      - book
      summary: update book
      description: Updating the existing book
      operationId: book#update
      parameters:
      - name: id
        in: path
        description: ID of the book
        required: true
        type: integer
      - name: UpdateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/BookUpdateRequestBody'
          required:
          - name
          - description
          - price
      responses:
        "200":
          description: OK response.
      schemes:
      - http
  /books:
    get:
      tags:
      - book
      summary: list book
      description: List all entries
      operationId: book#list
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/BookResponse'
      schemes:
      - http
definitions:
  BookCreateRequestBody:
    title: BookCreateRequestBody
    type: object
    properties:
      description:
        type: string
        description: Description of the book
        example: Books are human's best friend
        maxLength: 100
      id:
        type: integer
        description: ID of the book
        example: 1
        format: int32
      name:
        type: string
        description: Name of book
        example: book1
        maxLength: 100
      price:
        type: integer
        description: Price of the book
        example: 100
        format: int32
    example:
      description: Books are human's best friend
      id: 1
      name: book1
      price: 100
    required:
    - id
    - name
    - description
    - price
  BookCreateResponseBody:
    title: 'Mediatype identifier: application/vnd.book; view=default'
    type: object
    properties:
      description:
        type: string
        description: Description of the book
        example: Books are human's best friend
        maxLength: 100
      id:
        type: integer
        description: ID of the book
        example: 1
        format: int32
      name:
        type: string
        description: Name of book
        example: book1
        maxLength: 100
      price:
        type: integer
        description: Price of the book
        example: 100
        format: int32
    description: CreateResponseBody result type (default view)
    example:
      description: Books are human's best friend
      id: 1
      name: book1
      price: 100
    required:
    - id
    - name
    - description
    - price
  BookRemoveNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Book Not Found Error (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  BookResponse:
    title: 'Mediatype identifier: application/vnd.book; view=default'
    type: object
    properties:
      description:
        type: string
        description: Description of the book
        example: Books are human's best friend
        maxLength: 100
      id:
        type: integer
        description: ID of the book
        example: 1
        format: int32
      name:
        type: string
        description: Name of book
        example: book1
        maxLength: 100
      price:
        type: integer
        description: Price of the book
        example: 100
        format: int32
    description: Details of a book (default view)
    example:
      description: Books are human's best friend
      id: 1
      name: book1
      price: 100
    required:
    - id
    - name
    - description
    - price
  BookUpdateRequestBody:
    title: BookUpdateRequestBody
    type: object
    properties:
      description:
        type: string
        description: Description of the book
        example: Books are human's best friend
        maxLength: 100
      name:
        type: string
        description: Name of book
        example: book1
        maxLength: 100
      price:
        type: integer
        description: Price of the book
        example: 100
        format: int32
    example:
      description: Books are human's best friend
      name: book1
      price: 100
    required:
    - name
    - description
    - price
